IApple + IMango + Parking = 35 

3Apples + 2Mangoes + Parking = 75

4Apples + 3Mangoes + Parking = 105

5Apples + 5Mangoes + Parking =??? CAN WE PREDICT WITH IT 

In [1]:
import numpy as np

In [2]:
A = np.array([[1,1,1],[3,2,1],[4,3,1]])
B = np.array([[35],[75],[105]])

x = np.linalg.solve(A,B)
apple,mango,parking = x

In [3]:
y = 5*apple + 5*mango + 5*parking
y

print("Apple Price:", apple)
print("Mango Price:", mango)
print("Parking Price:", parking)
print("Predicted value for 5 Apples + 5 Mangoes + Parking:", y)

Apple Price: [10.]
Mango Price: [20.]
Parking Price: [5.]
Predicted value for 5 Apples + 5 Mangoes + Parking: [175.]


In [4]:
trafic = a*(t**2) + b*t + c

NameError: name 'a' is not defined

In [5]:
t = int(input("Time"))
np.array([1.0,3.0,2.0]).dot([t*t,t,1])

Time 12


182.0

In [6]:
model= np.array([[1.0, 3.0, 2.0]])
print(model)
t = np.array( [4, 5, 6, 7, 8, 9])
print(t)
t_sq = t*t
print(t_sq)
ones = np.ones(len(t))

[[1. 3. 2.]]
[4 5 6 7 8 9]
[16 25 36 49 64 81]


In [7]:
X = np.stack([t_sq, t, ones])
X

array([[16., 25., 36., 49., 64., 81.],
       [ 4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])