In [3]:
import pandas as pd
import numpy as np


In [29]:
x = np.array([13,14,18])
y = np.array([11,19,13])
n = len(x)

iteration = 2500
learning_rate = 0.001
m = 0
c = 0

# For MSE
curve = []

for i in range(iteration):

    random_index = np.random.randint(n)  
    xi = x[random_index]
    yi = y[random_index]

    y_predict = m*xi + c
    
    m1 = -2*xi*(yi-y_predict)
    m_old = m


    c1 = -2*(yi-y_predict)
    c_old = c


    m_s_e1 = (yi - y_predict)**2
    curve.append(m_s_e1)

    m = m-learning_rate*m1
    c = c-learning_rate*c1

    #print(f"Mse is: {m_s_e1}")
    
    if len(curve) > 1 and abs(curve[-2] - curve[-1]) < 1e-6:
        print(f"Final m: {m} \n Final c : {c}")
        break

print(f"Final Parameters: m = {m}, c = {c}")
print(f"Final predictions: {m*x + c}")

Final Parameters: m = 0.7606885731296944, c = 1.5612450379631364
Final predictions: [11.45019649 12.21088506 15.25363935]


In [21]:
df = pd.read_csv("match_stats.csv")
df.head()

Match_ID  Innings  Runs  Balls  Not_Out Batting_Avg  Strike_Rate  \
0  2023_012        1   101     85        1       101.0        118.8   
1  2023_017        1    13     15        1        13.0         86.7   
2  2023_018        1    30     17        1        30.0        176.5   
3  2023_146        1    12     19        0           -         63.2   
4  2023_153        1     0      6        1         0.0          0.0   

   Boundary_Runs  Sixes  Fours  Dot_Balls  Balls_Per_Boundary  Dot_Percentage  
0            101      0      1          9                   6            51.8  
1             13      0      0          2                   0            53.3  
2             30      0      0          2                   2            29.4  
3             12      0      0          2                   0            68.4  
4              0      0      0          0                   0           100.0

In [28]:
y = np.array(df['Runs'])
x = np.array(df['Balls'])
n = len(x)

iteration = 2500
learning_rate = 0.0001
m = 0
c = 0

# For MSE
curve = []

for i in range(iteration):

    random_index = np.random.randint(n)  
    xi = x[random_index]
    yi = y[random_index]

    y_predict = m*xi + c
    
    m1 = -2*xi*(yi-y_predict)
    m_old = m


    c1 = -2*(yi-y_predict)
    c_old = c


    m_s_e1 = (yi - y_predict)**2
    curve.append(m_s_e1)

    m = m-learning_rate*m1
    c = c-learning_rate*c1

    #print(f"Mse is: {m_s_e1}")
    
    if len(curve) > 1 and abs(curve[-2] - curve[-1]) < 1e-6:
        print(f"Final m: {m} \n Final c : {c}")
        break

print(f"Final Parameters: m = {m}, c = {c}")
#print(f"Final predictions: {m*x + c}")

x_new = float(input("Enter Balls to predict Runs: "))

# Predict balls faced using the learned equation
y_pred = m * x_new + c

print(f"Predicted Runs: {y_pred}")

Final Parameters: m = 1.2296024281973743, c = 0.13270538828044873


Enter Balls to predict Runs:  60


Predicted Runs: 73.9088510801229


In [37]:
x = df[['Balls','Strike_Rate','Dot_Percentage']].values
y = df['Runs'].values
n = len(x)
features= x.shape[1]

iteration = 2500
learning_rate = 0.00001
m = np.zeros(features)
c = 0

# For MSE
curve = []

for i in range(iteration):

    random_index = np.random.randint(n)  
    xi = x[random_index]
    yi = y[random_index]

    y_predict = np.dot(m,xi) + c
    
    m1 = -2*xi*(yi-y_predict)
    m_old = m


    c1 = -2*(yi-y_predict)
    c_old = c


    m_s_e1 = (yi - y_predict)**2
    curve.append(m_s_e1)

    m = m-learning_rate*m1
    c = c-learning_rate*c1

    #print(f"Mse is: {m_s_e1}")
    
    if len(curve) > 1 and abs(curve[-2] - curve[-1]) < 1e-6:
        print(f"Final m: {m} \n Final c : {c}")
        break

print(f"Final Parameters: m = {m}, c = {c}")
print(f"Final predictions: {m*x + c}")

x_new = []
balls = int(input("Enter balls"))
x_new.append(balls)
SR = float(input("Enter Strike Rate"))
x_new.append(SR)
Dot = float(input("Enter dot %"))
x_new.append(Dot)

x_new = np.array(x_new)
y_pred = np.dot(m, x_new) + c
print(f"Predicted Runs: {y_pred}")

Final Parameters: m = [ 1.17836158  0.10322719 -0.13413569], c = -6.270206928181104e-05
Final predictions: [[ 1.00160671e+02  1.22633272e+01 -6.94829155e+00]
 [ 1.76753610e+01  8.94973445e+00 -7.14949509e+00]
 [ 2.00320841e+01  1.82195359e+01 -3.94365205e+00]
 [ 2.23888073e+01  6.52389554e+00 -9.17494404e+00]
 [ 7.07010676e+00 -6.27020693e-05 -1.34136319e+01]
 [ 9.89823098e+01  1.61033785e+01 -4.94966974e+00]
 [ 7.42367167e+01  1.40904484e+01 -5.75448389e+00]
 [ 4.71344004e+01  1.23871998e+01 -8.04820423e+00]
 [ 4.71344004e+01  1.18710639e+01 -9.05422192e+00]
 [ 1.19014457e+02  8.88779814e+00 -8.23599420e+00]
 [ 2.35666045e+00  2.06453748e+01 -6.70684731e+00]
 [ 2.82806152e+01  1.72079094e+01 -6.70684731e+00]
 [ 6.36314625e+01  1.16646095e+01 -6.96170512e+00]
 [ 3.41724230e+01  1.67330644e+01 -7.40435291e+00]
 [ 3.65291462e+01  1.56491789e+01 -5.62034820e+00]
 [ 2.59238920e+01  5.16129667e+00 -1.03687517e+01]
 [ 6.95232704e+01  1.29446266e+01 -6.59953875e+00]
 [ 5.77396546e+01  1.17988

Enter balls 87
Enter Strike Rate 91.2
Enter dot % 57.8


Predicted Runs: 104.1786710088601
